package ro.bluedreamshisha.backend.constant;

public interface FieldErrorCode {

    /* Login */
    String LOGIN_USERNAME_BLANK = "LOGIN_USERNAME_BLANK";
    String LOGIN_PASSWORD_BLANK = "LOGIN_PASSWORD_BLANK";
    String LOGIN_USERNAME_NOT_EXISTS = "LOGIN_USERNAME_NOT_EXISTS";
    String LOGIN_PASSWORD_INCORRECT = "LOGIN_PASSWORD_INCORRECT";

    /* Register */
    String REGISTER_USERNAME_BLANK = "REGISTER_USERNAME_BLANK";
    String REGISTER_PASSWORD_BLANK = "REGISTER_PASSWORD_BLANK";
    String REGISTER_USERNAME_EXISTS = "REGISTER_USERNAME_EXISTS";
    String REGISTER_PASSWORD_WEEK = "REGISTER_PASSWORD_WEEK";
}
