package ro.bluedreamshisha.backend.constant;

public interface FieldErrorCode {

    String PREFIX = "FIELD_ERROR_";

    /* Login */
    String LOGIN_USERNAME_BLANK = PREFIX + "LOGIN_USERNAME_BLANK";
    String LOGIN_PASSWORD_BLANK = PREFIX + "LOGIN_PASSWORD_BLANK";
    String LOGIN_USERNAME_NOT_EXISTS = PREFIX + "LOGIN_USERNAME_NOT_EXISTS";
    String LOGIN_PASSWORD_INCORRECT = PREFIX + "LOGIN_PASSWORD_INCORRECT";

    /* Register */
    String REGISTER_USERNAME_BLANK = PREFIX + "REGISTER_USERNAME_BLANK";
    String REGISTER_PASSWORD_BLANK = PREFIX + "REGISTER_PASSWORD_BLANK";
    String REGISTER_USERNAME_EXISTS = PREFIX + "REGISTER_USERNAME_EXISTS";
    String REGISTER_PASSWORD_WEEK = PREFIX + "REGISTER_PASSWORD_WEEK";
    String REGISTER_USERNAME_MIN_LENGTH = PREFIX + "REGISTER_USERNAME_MIN_LENGTH";
    String REGISTER_USERNAME_MAX_LENGTH = PREFIX + "REGISTER_USERNAME_MAX_LENGTH";
}
